<?php
$data='{"AF": "Afghanistan",
		"AO": "Angola",
		"AL": "Albania",
		"AE": "United Arab Emirates",
		"AR": "Argentina",
		"AM": "Armenia",
		"AU": "Australia",
		"AT": "Austria",
		"AZ": "Azerbaijan",
		"BI": "Burundi",
		"BE": "Belgium",
		"BJ": "Benin",
		"BF": "Burkina Faso",
		"BD": "Bangladesh",
		"BG": "Bulgaria",
		"BA": "Bosnia and Herzegovina",
		"BY": "Belarus",
		"BZ": "Belize",
		"BO": "Bolivia",
		"BR": "Brazil",
		"BN": "Brunei Darussalam",
		"BT": "Bhutan",
		"BW": "Botswana",
		"CF": "Central African Republic",
		"CA": "Canada",
		"CH": "Switzerland",
		"CL": "Chile",
		"CN": "China",
		"CI": "Côte d' . "'" . 'Ivoire",
		"CM": "Cameroon",
		"CD": "Democratic Republic of the Congo",
		"CG": "Republic of Congo",
		"CO": "Colombia",
		"CR": "Costa Rica",
		"CU": "Cuba",
		"CZ": "Czech Republic",
		"DE": "Germany",
		"DJ": "Djibouti",
		"DK": "Denmark",
		"DO": "Dominican Republic",
		"DZ": "Algeria",
		"EC": "Ecuador",
		"EG": "Egypt",
		"ER": "Eritrea",
		"EE": "Estonia",
		"ET": "Ethiopia",
		"FI": "Finland",
		"FJ": "Fiji",
		"GA": "Gabon",
		"GB": "United Kingdom",
		"GE": "Georgia",
		"GH": "Ghana",
		"GN": "Guinea",
		"GM": "The Gambia",
		"GW": "Guinea-Bissau",
		"GQ": "Equatorial Guinea",
		"GR": "Greece",
		"GL": "Greenland",
		"GT": "Guatemala",
		"GY": "Guyana",
		"HN": "Honduras",
		"HR": "Croatia",
		"HT": "Haiti",
		"HU": "Hungary",
		"ID": "Indonesia",
		"IN": "India",
		"IE": "Ireland",
		"IR": "Iran",
		"IQ": "Iraq",
		"IS": "Iceland",
		"IL": "Israel",
		"IT": "Italy",
		"JM": "Jamaica",
		"JO": "Jordan",
		"JP": "Japan",
		"KZ": "Kazakhstan",
		"KE": "Kenya",
		"KG": "Kyrgyzstan",
		"KH": "Cambodia",
		"KR": "Republic of Korea",
		"XK": "Kosovo",
		"KW": "Kuwait",
		"LA": "Lao PDR",
		"LB": "Lebanon",
		"LR": "Liberia",
		"LY": "Libya",
		"LK": "Sri Lanka",
		"LS": "Lesotho",
		"LT": "Lithuania",
		"LU": "Luxembourg",
		"LV": "Latvia",
		"MA": "Morocco",
		"MD": "Moldova",
		"MG": "Madagascar",
		"MX": "Mexico",
		"MK": "Macedonia",
		"ML": "Mali",
		"MM": "Myanmar",
		"ME": "Montenegro",
		"MN": "Mongolia",
		"MZ": "Mozambique",
		"MR": "Mauritania",
		"MW": "Malawi",
		"MY": "Malaysia",
		"NA": "Namibia",
		"NE": "Niger",
		"NG": "Nigeria",
		"NI": "Nicaragua",
		"NL": "Netherlands",
		"NO": "Norway",
		"NP": "Nepal",
		"NZ": "New Zealand",
		"OM": "Oman",
		"PK": "Pakistan",
		"PA": "Panama",
		"PE": "Peru",
		"PH": "Philippines",
		"PG": "Papua New Guinea",
		"PL": "Poland",
		"KP": "Dem. Rep. Korea",
		"PT": "Portugal",
		"PY": "Paraguay",
		"PS": "Palestine",
		"QA": "Qatar",
		"RO": "Romania",
		"RU": "Russian Federation",
		"RW": "Rwanda",
		"EH": "Western Sahara",
		"SA": "Saudi Arabia",
		"SD": "Sudan",
		"SS": "South Sudan",
		"SN": "Senegal",
		"SL": "Sierra Leone",
		"SV": "El Salvador",
		"RS": "Serbia",
		"SR": "Suriname",
		"SK": "Slovakia",
		"SI": "Slovenia",
		"SE": "Sweden",
		"SZ": "Swaziland",
		"SY": "Syria",
		"TD": "Chad",
		"TG": "Togo",
		"TH": "Thailand",
		"TJ": "Tajikistan",
		"TM": "Turkmenistan",
		"TL": "Timor-Leste",
		"TN": "Tunisia",
		"TR": "Turkey",
		"TW": "Taiwan",
		"TZ": "Tanzania",
		"UG": "Uganda",
		"UA": "Ukraine",
		"UY": "Uruguay",
		"US": "United States",
		"UZ": "Uzbekistan",
		"VE": "Venezuela",
		"VN": "Vietnam",
		"VU": "Vanuatu",
		"YE": "Yemen",
		"ZA": "South Africa",
		"ZM": "Zambia",
		"ZW": "Zimbabwe",
		"SO": "Somalia",
		"GF": "France",
		"FR": "France",
		"ES": "Spain",
		"AW": "Aruba",
		"AI": "Anguilla",
		"AD": "Andorra",
		"AG": "Antigua and Barbuda",
		"BS": "Bahamas",
		"BM": "Bermuda",
		"BB": "Barbados",
		"KM": "Comoros",
		"CV": "Cape Verde",
		"KY": "Cayman Islands",
		"DM": "Dominica",
		"FK": "Falkland Islands",
		"FO": "Faeroe Islands",
		"GD": "Grenada",
		"HK": "Hong Kong",
		"KN": "Saint Kitts and Nevis",
		"LC": "Saint Lucia",
		"LI": "Liechtenstein",
		"MF": "Saint Martin (French)",
		"MV": "Maldives",
		"MT": "Malta",
		"MS": "Montserrat",
		"MU": "Mauritius",
		"NC": "New Caledonia",
		"NR": "Nauru",
		"PN": "Pitcairn Islands",
		"PR": "Puerto Rico",
		"PF": "French Polynesia",
		"SG": "Singapore",
		"SB": "Solomon Islands",
		"ST": "São Tomé and Principe",
		"SX": "Saint Martin (Dutch)",
		"SC": "Seychelles",
		"TC": "Turks and Caicos Islands",
		"TO": "Tonga",
		"TT": "Trinidad and Tobago",
		"VC": "Saint Vincent and the Grenadines",
		"VG": "British Virgin Islands",
		"VI": "United States Virgin Islands",
		"CY": "Cyprus",
		"RE": "Reunion (France)",
		"YT": "Mayotte (France)",
		"MQ": "Martinique (France)",
		"GP": "Guadeloupe (France)",
		"CW": "Curaco (Netherlands)",
		"IC": "Canary Islands (Spain)"
}';
	$json = json_decode($data,true);
	foreach($json as $k => $v ){
		$countryCode[]=sprintf('%s',$k);
	}
	foreach($json as $k => $v ){
		$countryEn[]=sprintf('%s',$v);
	}
	$countryCh='阿富汗，安哥拉，阿爾巴尼亞，阿拉伯聯合酋長國，阿根廷，亞美尼亞，澳大利亞，奧地利，阿塞拜疆，蒲隆地，比利時，貝寧，布吉納法索，孟加拉，保加利亞，波斯尼亞和黑塞哥維那，白俄羅斯，貝里斯，玻利維亞，巴西，文萊達魯薩蘭國，不丹，博茨瓦納，中非共和國，加拿大，瑞士，智利，中國大陸，象牙海岸，喀麥隆，剛果民主共和國，剛果共和國，哥倫比亞，哥斯大黎加，古巴，捷克共和國，德國，吉布提，丹麥，多明尼加，阿爾及利亞，厄瓜多，埃及，厄立特里亞，愛沙尼亞，衣索比亞，芬蘭，斐濟，加彭，英國，喬治亞，加納，幾內亞，岡比亞，幾內亞比索，赤道幾內亞，希臘，格陵蘭，瓜地馬拉，蓋亞那共和國，宏都拉斯，克羅地亞，海地，匈牙利，印尼，印度，愛爾蘭，伊朗，伊拉克，冰島，以色列，意大利，牙買加，約旦，日本，哈薩克斯坦，肯尼亞，吉爾吉斯斯坦，柬埔寨，大韓民國，科索沃，科威特，寮國，黎巴嫩，利比里亞，利比亞，斯里蘭卡，萊索托，立陶宛，盧森堡，拉脫維亞，摩洛哥，摩爾多瓦，馬達加斯加，墨西哥，馬其頓，馬里，緬甸，黑山，蒙古，莫桑比克，毛里求斯，馬拉維，馬來西亞，那米比亞，尼日爾，奈及利亞，尼加拉瓜，荷蘭，挪威，尼泊爾，紐西蘭，阿曼，巴基斯坦，巴拿馬共和國，秘魯，菲律賓，巴布亞紐幾內亞，波蘭，Dem。韓國，葡萄牙，巴拉圭共和國，巴勒斯坦，卡塔爾，羅馬尼亞，俄羅斯，盧旺達，西撒哈拉，沙特阿拉伯，蘇丹，南蘇丹，塞內加爾，塞拉利昂，薩爾瓦多，塞爾維亞，蘇利南，斯洛伐克，斯洛文尼亞，瑞典，斯威士蘭，敘利亞，乍得，多哥，泰國，塔吉克斯坦，土庫曼斯坦，東帝汶，突尼斯，土耳其，台灣，坦桑尼亞，烏干達，烏克蘭，烏拉圭，美國，烏茲別克斯坦，委內瑞拉，越南，瓦努阿圖，也門，南非，贊比亞，津巴布韋，索馬里，法屬圭亞那，法國，西班牙，阿魯巴，安圭拉，安道爾，安提瓜和巴布達，巴哈馬，百慕大，巴巴多斯，科摩羅，維德角，開曼群島，多米尼加，福克蘭群島，法羅群島，格林納達，香港，聖基茨和尼維斯，聖露西亞，列支敦士登，聖馬丁（法國），馬爾代夫，馬耳他，蒙特塞拉特，毛里求斯，新喀裡多尼亞，瑙魯，皮特凱恩群，波多黎各，法屬波利尼西亞，新加坡，索羅門群島，聖多美和普林西比，聖馬丁（荷蘭），塞舌爾，特克斯和凱科斯群島，湯加，特立尼達和多巴哥，聖文森特和格林納丁斯，英屬維爾京群島，美屬維爾京群島，塞浦路斯，留尼旺（法國），馬約特島（法國），馬提尼克島（法國），瓜德羅普島（法國），庫拉科（荷蘭），加那利群島（西班牙）';
	$countryCh=explode('，',$countryCh);
	$country=[$countryCode,$countryEn,$countryCh];

	// echo sizeof($countryEn);
	// echo "<br>";
	// echo sizeof($countryCode);
	// echo "<br>";
	// echo sizeof($countryCh);
	// echo "<br>";
	// print_r($countryEn);
	// print_r($countryCh);




	

?>