<?php
$data='{"AF": "Afghanistan",
		"AO": "Angola",
		"AL": "Albania",
		"AE": "United Arab Emirates",
		"AR": "Argentina",
		"AM": "Armenia",
		"AU": "Australia",
		"AT": "Austria",
		"AZ": "Azerbaijan",
		"BI": "Burundi",
		"BE": "Belgium",
		"BJ": "Benin",
		"BF": "Burkina Faso",
		"BD": "Bangladesh",
		"BG": "Bulgaria",
		"BA": "Bosnia and Herzegovina",
		"BY": "Belarus",
		"BZ": "Belize",
		"BO": "Bolivia",
		"BR": "Brazil",
		"BN": "Brunei Darussalam",
		"BT": "Bhutan",
		"BW": "Botswana",
		"CF": "Central African Republic",
		"CA": "Canada",
		"CH": "Switzerland",
		"CL": "Chile",
		"CN": "China",
		"CI": "Côte d' . "'" . 'Ivoire",
		"CM": "Cameroon",
		"CD": "Democratic Republic of the Congo",
		"CG": "Republic of Congo",
		"CO": "Colombia",
		"CR": "Costa Rica",
		"CU": "Cuba",
		"CZ": "Czech Republic",
		"DE": "Germany",
		"DJ": "Djibouti",
		"DK": "Denmark",
		"DO": "Dominican Republic",
		"DZ": "Algeria",
		"EC": "Ecuador",
		"EG": "Egypt",
		"ER": "Eritrea",
		"EE": "Estonia",
		"ET": "Ethiopia",
		"FI": "Finland",
		"FJ": "Fiji",
		"GA": "Gabon",
		"GB": "United Kingdom",
		"GE": "Georgia",
		"GH": "Ghana",
		"GN": "Guinea",
		"GM": "The Gambia",
		"GW": "Guinea-Bissau",
		"GQ": "Equatorial Guinea",
		"GR": "Greece",
		"GL": "Greenland",
		"GT": "Guatemala",
		"GY": "Guyana",
		"HN": "Honduras",
		"HR": "Croatia",
		"HT": "Haiti",
		"HU": "Hungary",
		"ID": "Indonesia",
		"IN": "India",
		"IE": "Ireland",
		"IR": "Iran",
		"IQ": "Iraq",
		"IS": "Iceland",
		"IL": "Israel",
		"IT": "Italy",
		"JM": "Jamaica",
		"JO": "Jordan",
		"JP": "Japan",
		"KZ": "Kazakhstan",
		"KE": "Kenya",
		"KG": "Kyrgyzstan",
		"KH": "Cambodia",
		"KR": "Republic of Korea",
		"XK": "Kosovo",
		"KW": "Kuwait",
		"LA": "Lao PDR",
		"LB": "Lebanon",
		"LR": "Liberia",
		"LY": "Libya",
		"LK": "Sri Lanka",
		"LS": "Lesotho",
		"LT": "Lithuania",
		"LU": "Luxembourg",
		"LV": "Latvia",
		"MA": "Morocco",
		"MD": "Moldova",
		"MG": "Madagascar",
		"MX": "Mexico",
		"MK": "Macedonia",
		"ML": "Mali",
		"MM": "Myanmar",
		"ME": "Montenegro",
		"MN": "Mongolia",
		"MZ": "Mozambique",
		"MR": "Mauritania",
		"MW": "Malawi",
		"MY": "Malaysia",
		"NA": "Namibia",
		"NE": "Niger",
		"NG": "Nigeria",
		"NI": "Nicaragua",
		"NL": "Netherlands",
		"NO": "Norway",
		"NP": "Nepal",
		"NZ": "New Zealand",
		"OM": "Oman",
		"PK": "Pakistan",
		"PA": "Panama",
		"PE": "Peru",
		"PH": "Philippines",
		"PG": "Papua New Guinea",
		"PL": "Poland",
		"KP": "Dem. Rep. Korea",
		"PT": "Portugal",
		"PY": "Paraguay",
		"PS": "Palestine",
		"QA": "Qatar",
		"RO": "Romania",
		"RU": "Unnamed",
		"RW": "Rwanda",
		"EH": "Western Sahara",
		"SA": "Saudi Arabia",
		"SD": "Sudan",
		"SS": "South Sudan",
		"SN": "Senegal",
		"SL": "Sierra Leone",
		"SV": "El Salvador",
		"RS": "Serbia",
		"SR": "Suriname",
		"SK": "Slovakia",
		"SI": "Slovenia",
		"SE": "Sweden",
		"SZ": "Swaziland",
		"SY": "Syria",
		"TD": "Chad",
		"TG": "Togo",
		"TH": "Thailand",
		"TJ": "Tajikistan",
		"TM": "Turkmenistan",
		"TL": "Timor-Leste",
		"TN": "Tunisia",
		"TR": "Turkey",
		"TW": "Taiwan",
		"TZ": "Tanzania",
		"UG": "Uganda",
		"UA": "Ukraine",
		"UY": "Uruguay",
		"US": "United States",
		"UZ": "Uzbekistan",
		"VE": "Venezuela",
		"VN": "Vietnam",
		"VU": "Vanuatu",
		"YE": "Yemen",
		"ZA": "South Africa",
		"ZM": "Zambia",
		"ZW": "Zimbabwe",
		"SO": "Somalia",
		"GF": "France",
		"FR": "France",
		"ES": "Spain",
		"AW": "Aruba",
		"AI": "Anguilla",
		"AD": "Andorra",
		"AG": "Antigua and Barbuda",
		"BS": "Bahamas",
		"BM": "Bermuda",
		"BB": "Barbados",
		"KM": "Comoros",
		"CV": "Cape Verde",
		"KY": "Cayman Islands",
		"DM": "Dominica",
		"FK": "Falkland Islands",
		"FO": "Faeroe Islands",
		"GD": "Grenada",
		"HK": "Hong Kong",
		"KN": "Saint Kitts and Nevis",
		"LC": "Saint Lucia",
		"LI": "Liechtenstein",
		"MF": "Saint Martin (French)",
		"MV": "Maldives",
		"MT": "Malta",
		"MS": "Montserrat",
		"MU": "Mauritius",
		"NC": "New Caledonia",
		"NR": "Nauru",
		"PN": "Pitcairn Islands",
		"PR": "Puerto Rico",
		"PF": "French Polynesia",
		"SG": "Singapore",
		"SB": "Solomon Islands",
		"ST": "São Tomé and Principe",
		"SX": "Saint Martin (Dutch)",
		"SC": "Seychelles",
		"TC": "Turks and Caicos Islands",
		"TO": "Tonga",
		"TT": "Trinidad and Tobago",
		"VC": "Saint Vincent and the Grenadines",
		"VG": "British Virgin Islands",
		"VI": "United States Virgin Islands",
		"CY": "Cyprus",
		"RE": "Reunion (France)",
		"YT": "Mayotte (France)",
		"MQ": "Martinique (France)",
		"GP": "Guadeloupe (France)",
		"CW": "Curaco (Netherlands)",
		"IC": "Canary Islands (Spain)"
}';
	$json = json_decode($data,true);
	foreach($json as $k => $v ){
		$countryCode[]=sprintf('%s',$k);
	}
	foreach($json as $k => $v ){
		$countryEn[]=sprintf('%s',$v);
	}
	$countryCh='阿富汗，安哥拉，阿尔巴尼亚，阿拉伯联合酋长国，阿根廷，亚美尼亚，澳大利亚，奥地利，阿塞拜疆，布隆迪，比利时，贝宁，布基纳法索，孟加拉国，保加利亚，波斯尼亚和黑塞哥维那，白俄罗斯，伯利兹，玻利维亚，巴西，文莱达鲁萨兰国，不丹博茨瓦纳，中非共和国，加拿大，瑞士，智利，中国，科特迪瓦，喀麦隆，刚果民主共和国，刚果共和国，哥伦比亚，哥斯达黎加，古巴，捷克共和国，德国，吉布提，丹麦，多米尼加共和国，阿尔及利亚，厄瓜多尔，埃及，厄立特里亚，爱沙尼亚，埃塞俄比亚，芬兰，斐济，加蓬，英国，乔治亚，加纳，几内亚，冈比亚，几内亚比绍，赤道几内亚，希腊，格陵兰，危地马拉，圭亚那，洪都拉斯，克罗地亚，海地，匈牙利，印度尼西亚，印度，爱尔兰，伊朗，伊拉克，冰岛，以色列，意大利，牙买加，约旦，日本，哈萨克斯坦，肯尼亚，吉尔吉斯斯坦，柬埔寨，大韩民国，科索沃，科威特，老挝，黎巴嫩，利比里亚，利比亚，斯里兰卡，莱索托，立陶宛，卢森堡，拉脱维亚，摩洛哥，摩尔多瓦，马达加斯加，墨西哥，马其顿，马里，缅甸，黑山，蒙古，莫桑比克，毛里求斯，马拉维，马来西亚，Na米比亚，尼日尔，尼日利亚，尼加拉瓜，荷兰，挪威，尼泊尔，新西兰，阿曼，巴基斯坦，巴拿马，秘鲁，菲律宾，巴布亚新几内亚，波兰，Dem。韩国，葡萄牙，巴拉圭，巴勒斯坦，卡塔尔，罗马尼亚，未命名，卢旺达，西撒哈拉，沙特阿拉伯，苏丹，南苏丹，塞内加尔，塞拉利昂，萨尔瓦多，塞尔维亚，苏里南，斯洛伐克，斯洛文尼亚，瑞典，斯威士兰，叙利亚乍得，多哥，泰国，塔吉克斯坦，土库曼斯坦，东帝汶，突尼斯，土耳其，台湾，坦桑尼亚，乌干达，乌克兰，乌拉圭，美国，乌兹别克斯坦，委内瑞拉，越南，瓦努阿图，也门，南非，赞比亚，津巴布韦，索马里法国，法国，西班牙，阿鲁巴，安圭拉，安道尔，安提瓜和巴布达，巴哈马，百慕大，巴巴多斯，科摩罗，佛得角，开曼群岛，多米尼加，福克兰群岛，法罗群岛，格林纳达，香港，圣基茨和尼维斯，圣露西亚，列支敦士登，圣马丁（法国），马尔代夫，马耳他，蒙特塞拉特，毛里求斯，新喀里多尼亚，瑙鲁，皮特凯恩群岛，波多黎各，法属波利尼西亚，新加坡，所罗门群岛，圣多美和普林西比，圣马丁（荷兰），塞舌尔，特克斯和凯科斯群岛，汤加，特立尼达和多巴哥，圣文森特和格林纳丁斯，英属维尔京群岛，美属维尔京群岛，塞浦路斯，留尼旺（法国），马约特岛（法国），马提尼克岛（法国），瓜德罗普岛（法国），库拉科（荷兰），加那利群岛（西班牙）';
	$countryCh=explode('，',$countryCh);
	echo sizeof($countryEn);
	echo sizeof($countryCode);




	

?>